default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: ToggleMe_development
  username: ToggleMe
  password:
  host: localhost

test:
  <<: *default
  database: ToggleMe_test
  username: ToggleMe
  password:
  host: localhost

production:
  <<: *default
  database: ToggleMe_production
  username: ToggleMe
  password: <%= ENV['TOGGLEME_DATABASE_PASSWORD'] %>
